### ISSUE TITLE
 In deep_metric_learning/lib/functions/angular_loss.py, sq_tan_alpha = np.tan(alpha) ** 2 sq_tan_alpha = 1.0 / 4

### ISSUE THREAD

**Issue by zhfwyy** [ronekko/deep_metric_learning#6]
In deep_metric_learning/lib/functions/angular_loss.py
sq_tan_alpha = np.tan(alpha) ** 2 
sq_tan_alpha = 1.0 / 4
Is the second "sq_tan_alpha = 1.0 / 4" right?

**Comment by ronekko** [comment]
Thank you for reporting the issue.
Ah, this must be a bug, although I actually checked only `angular_mc_loss` function.

**Comment by ronekko** [comment]
Fixed. Thank you!

**Comment by zhfwyy** [comment]
THank you very much!
