### ISSUE TITLE
/lib/datasets/cars196_downloader.py   "http://imagenet.stanford.edu/internal/car196/" can't open

### ISSUE THREAD

**Issue by zhfwyy** [ronekko/deep_metric_learning#8]
I can use ftp://cs.stanford.edu/cs/cvgl/ to download CARS196.zip

**Comment by zhfwyy** [comment]
If I want to set download data path, I should set data_path?

**Comment by zhfwyy** [comment]
If I want to set download data path, I should set data_path?

**Comment by ronekko** [comment]
Thank you.
I updated to the new URL.
